title: "CardioPredict: Assessing Heart Disease Risk"
author: "Joey Wu, He Ma, Sandy Gross and Doris Wang"
date: "2023-12-01"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
    - references.bib
