services:
  disease_pred:
    image: sandragross/522_project_10:a7b038e
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 15G
    platform: linux/amd64
      
