name: 522-project-disease
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.1.2
  - ipykernel
  - jinja2
  - matplotlib[version='>=3.8.0']
  - nb_conda_kernels
  - pandas[version='>=2.1.1']
  - pip[version='>=23.2.1']
  - python==3.10
  - requests[version='>=2.24.0']
  - scikit-learn[version='>=1.3.1']
  - vega_datasets
  - vegafusion
  - vegafusion-jupyter
  - vegafusion-python-embed
  - vl-convert-python
  - pip>=23.2.1   
  - pip:
    - imblearn==0.0
