name: 522-project-disease
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.1.2
  - ipykernel=6.26.0
  - jinja2=3.1.2
  - matplotlib=3.8.0
  - nb_conda_kernels=2.3.1 
  - pandas=2.1.1
  - numpy=1.26.0 
  - pip=23.2.1
  - python==3.10
  - requests=2.24.0
  - scikit-learn=1.3.1
  - vega_datasets= 0.9.0 
  - vegafusion=1.4.3
  - vegafusion-jupyter=1.4.3
  - vegafusion-python-embed=1.4.3
  - vl-convert-python=1.1.0
  - pip>=23.2.1
  - pytest=7.4.3 
  - pip:
    - imblearn==0.0
